version: "3.9"

services:
  web:
    container_name: pixwasm-web
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      - PORT=1997
    ports:
      - "1997:1997"
    restart: unless-stopped
