/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_compressionresult_free: (a: number, b: number) => void;
export const analyze_image_metrics: (a: number, b: number) => [number, number, number];
export const calculate_image_quality_score: (a: number, b: number, c: number, d: number) => [number, number, number];
export const compare_avif_candidate_quality: (a: number, b: number, c: number, d: number) => [number, number, number];
export const compare_avif_candidate_rgba: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number];
export const compare_image_quality_for_guardrails: (a: number, b: number, c: number, d: number) => [number, number, number];
export const compress_image: (a: number, b: number, c: number) => [number, number, number];
export const compress_image_to_format: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const compress_image_to_format_with_options: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number];
export const compress_png_with_deflate: (a: number, b: number, c: number) => [number, number, number];
export const compressionresult_bytes: (a: number) => [number, number];
export const compressionresult_ext: (a: number) => [number, number];
export const compressionresult_mime: (a: number) => [number, number];
export const create_avif_encoding_plan: (a: number, b: number, c: number, d: number) => [number, number, number];
export const create_avif_encoding_plan_rgba: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number];
export const create_zip_from_items: (a: any) => [number, number, number, number];
export const generate_favicon: (a: number, b: number) => [number, number, number];
export const generate_share_placeholder: (a: number, b: number) => [number, number, number];
export const generate_share_placeholder_from_rgba: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number];
export const generate_share_preview_thumbnail: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const generate_share_preview_thumbnail_from_rgba: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const generate_share_thumbnail: (a: number, b: number) => [number, number, number, number];
export const compare_image_quality: (a: number, b: number, c: number, d: number) => [number, number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
