name = "picbind-worker"
main = "src/index.ts"
compatibility_date = "2026-04-20"

routes = [
  { pattern = "api.picbind.com", custom_domain = true }
]

[[kv_namespaces]]
binding = "METRICS_KV"
id = "ffd6a9e2ce924cf2a4b93b782d525810"

[[r2_buckets]]
binding = "SHARE_IMAGES_R2"
bucket_name = "picbind-bucket"

[[durable_objects.bindings]]
name = "METRICS_COUNTER"
class_name = "MetricsCounter"

[[durable_objects.bindings]]
name = "REALTIME_ROOMS"
class_name = "ShareRoomObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MetricsCounter"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["ShareRoomObject"]

[vars]
DEV_MODE = "0"
ADMIN_KEY = "64b5cdf2a1f5b998c54a045fb4f89006efb41513e94d16712bdb167a016010fc"
FILE_TRANSFER_MODE = "r2"
MAX_IMAGE_TRANSFER_SIZE_MB = "10"
R2_RTT_THRESHOLD_MS = "200"
R2_FILE_TTL_SECONDS = "1800"
R2_BUCKET_NAME = "picbind-bucket"
R2_ACCOUNT_ID = "a3af9fe482ea605e4cc8b2496a45b806"
SITE_URL = "https://picbind.com"
ALLOWED_ORIGINS = "https://picbind.com"
TURN_TOKEN_ID = "b7372f7025974b852a03b856a4c3461f"

[[ratelimits]]
name = "GLOBAL_LIMITER"
namespace_id = "1001"
simple = { limit = 120, period = 60 }

[[ratelimits]]
name = "ROUTE_LIMITER"
namespace_id = "1002"
simple = { limit = 60, period = 60 }

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
