import type { Lang } from "@/locales";

const zh = {
  back: "返回首页",
  room: "分享房间",
  copy: "复制房间链接",
  copied: "链接已复制",
  shareCreatedTitle: "分享房间已创建",
  shareLink: "分享链接",
  expires: "房间将在无活动 30 分钟后过期",
  closeDialog: "关闭",
  invalid: "分享链接无效",
  workspace: "图片工作区",
  gallery: "图片库",
  review: "协作查看",
  reviewImage: "进入协作",
  previewImage: "预览图片",
  holdThumbnail: "按住查看缩略图",
  backToGallery: "返回图片库",
  selectTool: "选择",
  handTool: "移动画布",
  arrowTool: "箭头",
  lineTool: "直线",
  solidLine: "实线",
  dashedLine: "虚线",
  dottedLine: "圆点线",
  rectangleTool: "矩形",
  circleTool: "圆形",
  penTool: "画笔",
  textTool: "文字",
  emojiTool: "表情",
  annotationColor: "标注颜色",
  lineThickness: "线条粗细",
  laserTool: "激光笔",
  zoomIn: "放大",
  zoomOut: "缩小",
  fitView: "适应窗口",
  resetView: "重置视角",
  undo: "撤销",
  redo: "重做",
  followPresenter: "跟随演示者",
  present: "演示",
  upload: "选择图片",
  chooseImageSource: "选择图片来源",
  localImages: "本地图片",
  localImagesHint: "从当前设备选择图片",
  compressedImages: "已压缩图片",
  compressedImagesHint: "使用当前网站缓存的压缩结果",
  compressedPickerTitle: "选择已压缩图片",
  noCompressedImages: "当前浏览器还没有已压缩图片",
  goCompress: "去压缩图片",
  addSelected: "添加所选图片",
  removeCachedImage: "移除缓存图片",
  clearCompressedImages: "清除全部缓存",
  cancel: "取消",
  confirm: "确定",
  compressionSuggested: "建议先压缩图片",
  largeImageSuggestion: "所选本地图片超过 1 MB，压缩后发送会更快。",
  weakNetworkSuggestion: "当前网络延迟较高，超过 300 KB 的图片建议先压缩。",
  continueOriginal: "继续使用原图",
  cancelTransfer: "取消发送",
  transferCancelled: "传输已取消",
  transferInterrupted: "页面刷新导致传输中断，请重新发送",
  uploading: "正在发送",
  drop: "拖入图片开始传输",
  dropHint: "支持常见图片格式，单张大小以房间配置为准",
  guestEmpty: "选择或拖入图片",
  cached: "图片保存在当前浏览器",
  sent: "已发送",
  received: "已接收",
  send: "发送图片",
  waitingToSend: "等待发送",
  waitingForSender: "等待对方发送",
  preparingPreview: "正在生成占位信息",
  previewFailed: "图片占位信息生成失败",
  previewOnly: "32×32 预览",
  download: "下载图片",
  deleteImage: "删除图片",
  participants: "匿名成员",
  owner: "匿名 Owner",
  guest: "匿名 Guest",
  you: "你",
  online: "在线",
  offline: "离线",
  kickMember: "移出房间",
  latency: "延迟",
  packetLoss: "丢包率",
  p2pMode: "P2P 直连",
  relayMode: "WebSocket 中继",
  r2Mode: "R2 中继传输",
  activity: "传输消息",
  noActivity: "暂无传输消息",
  clearActivity: "清除消息",
  testMessage: "发送文本消息",
  textPlaceholder: "输入消息",
  sendMessage: "发送",
  quickReactions: "快捷表情",
  messageSending: "等待对方确认",
  messageSent: "对方已接收",
  messageReceived: "收到普通消息",
  waiting: "等待另一位成员",
  connecting: "正在建立实时连接",
  connected: "实时通道已连接",
  failed: "连接失败",
  sending: "正在发送",
  receiving: "正在接收",
  complete: "传输完成",
  awaitingReceipt: "已发送，等待对方确认",
  cacheFailed: "本地缓存失败",
  transferFailed: "图片传输失败",
  imageOnly: "只能传输图片文件",
  tooLarge: "图片超过房间大小限制",
  temporaryLeave: "临时离开",
  leaveRoom: "退出房间",
  closeRoom: "退出并销毁房间",
  confirmLeaveRoom: "离开房间将断开实时连接。确定继续吗？",
  confirmClose: "退出后房间将立即销毁，所有成员都会被移出。确定继续吗？",
};

const en: typeof zh = {
  back: "Back to home",
  room: "Share room",
  copy: "Copy room link",
  copied: "Link copied",
  shareCreatedTitle: "Share room created",
  shareLink: "Share link",
  expires: "This room expires after 30 minutes of inactivity",
  closeDialog: "Close",
  invalid: "Invalid share link",
  workspace: "Image workspace",
  gallery: "Gallery",
  review: "Review",
  reviewImage: "Review image",
  previewImage: "Preview image",
  holdThumbnail: "Hold to view thumbnail",
  backToGallery: "Back to gallery",
  selectTool: "Select",
  handTool: "Pan canvas",
  arrowTool: "Arrow",
  lineTool: "Line",
  solidLine: "Solid",
  dashedLine: "Dashed",
  dottedLine: "Dotted",
  rectangleTool: "Rectangle",
  circleTool: "Circle",
  penTool: "Pen",
  textTool: "Text",
  emojiTool: "Emoji",
  annotationColor: "Annotation color",
  lineThickness: "Line thickness",
  laserTool: "Laser pointer",
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  fitView: "Fit to view",
  resetView: "Reset view",
  undo: "Undo",
  redo: "Redo",
  followPresenter: "Follow presenter",
  present: "Present",
  upload: "Choose images",
  chooseImageSource: "Choose image source",
  localImages: "Local images",
  localImagesHint: "Choose images from this device",
  compressedImages: "Compressed images",
  compressedImagesHint: "Use compressed results cached by this site",
  compressedPickerTitle: "Choose compressed images",
  noCompressedImages: "No compressed images are cached in this browser",
  goCompress: "Compress images",
  addSelected: "Add selected images",
  removeCachedImage: "Remove cached image",
  clearCompressedImages: "Clear all cache",
  cancel: "Cancel",
  confirm: "Confirm",
  compressionSuggested: "Compression recommended",
  largeImageSuggestion: "Local images over 1 MB will transfer faster after compression.",
  weakNetworkSuggestion: "Network latency is high. Compress images over 300 KB first.",
  continueOriginal: "Continue with originals",
  cancelTransfer: "Cancel transfer",
  transferCancelled: "Transfer cancelled",
  transferInterrupted: "Transfer interrupted by page refresh. Send it again.",
  uploading: "Sending",
  drop: "Drop images to transfer",
  dropHint: "Common image formats; the room sets the size limit",
  guestEmpty: "Choose or drop images",
  cached: "Images are stored in this browser",
  sent: "Sent",
  received: "Received",
  send: "Send image",
  waitingToSend: "Waiting to send",
  waitingForSender: "Waiting for sender",
  preparingPreview: "Preparing placeholder",
  previewFailed: "Placeholder generation failed",
  previewOnly: "32×32 preview",
  download: "Download image",
  deleteImage: "Delete image",
  participants: "Anonymous members",
  owner: "Anonymous Owner",
  guest: "Anonymous Guest",
  you: "You",
  online: "Online",
  offline: "Offline",
  kickMember: "Remove from room",
  latency: "RTT",
  packetLoss: "Packet loss",
  p2pMode: "P2P direct",
  relayMode: "WebSocket relay",
  r2Mode: "R2 relay transfer",
  activity: "Transfer messages",
  noActivity: "No transfer messages yet",
  clearActivity: "Clear messages",
  testMessage: "Send a text message",
  textPlaceholder: "Type a message",
  sendMessage: "Send",
  quickReactions: "Quick reactions",
  messageSending: "Waiting for peer confirmation",
  messageSent: "Received by peer",
  messageReceived: "Regular message received",
  waiting: "Waiting for another member",
  connecting: "Establishing realtime connection",
  connected: "Realtime channel connected",
  failed: "Connection failed",
  sending: "Sending",
  receiving: "Receiving",
  complete: "Transfer complete",
  awaitingReceipt: "Sent, waiting for receiver confirmation",
  cacheFailed: "Local cache failed",
  transferFailed: "Image transfer failed",
  imageOnly: "Only image files can be transferred",
  tooLarge: "Image exceeds the room size limit",
  temporaryLeave: "Leave temporarily",
  leaveRoom: "Leave room",
  closeRoom: "Exit and close room",
  confirmLeaveRoom: "Leaving the room will disconnect the realtime session. Continue?",
  confirmClose: "Closing the room removes every member immediately. Continue?",
};

export type ShareRoomLabels = typeof zh;

export function getShareRoomLabels(
  lang: Lang,
  maxImageTransferSize: number | null = null,
): ShareRoomLabels {
  const labels = lang === "zh" ? zh : en;
  if (!maxImageTransferSize) return labels;
  const sizeMb = maxImageTransferSize / 1024 / 1024;
  const sizeText = `${Number(sizeMb.toFixed(2))} MB`;
  return {
    ...labels,
    dropHint:
      lang === "zh"
        ? `支持常见图片格式，单张最大 ${sizeText}`
        : `Common image formats, up to ${sizeText} each`,
    tooLarge:
      lang === "zh"
        ? `图片超过 ${sizeText}`
        : `Image exceeds ${sizeText}`,
  };
}
