import type { Lang } from "@/locales";

const zh = {
  back: "返回首页",
  room: "分享房间",
  copy: "复制房间链接",
  copied: "链接已复制",
  shareCreatedTitle: "分享房间已创建",
  shareLink: "分享链接",
  expires: "房间将在 30 分钟后过期",
  closeDialog: "关闭",
  invalid: "分享链接无效",
  workspace: "图片工作区",
  upload: "选择图片",
  uploading: "正在发送",
  drop: "拖入图片开始传输",
  dropHint: "支持常见图片格式，单张大小以房间配置为准",
  guestEmpty: "选择或拖入图片",
  cached: "图片保存在当前浏览器",
  sent: "已发送",
  received: "已接收",
  send: "发送图片",
  waitingToSend: "等待发送",
  waitingForSender: "等待对方发送",
  preparingPreview: "正在生成占位信息",
  previewFailed: "图片占位信息生成失败",
  previewOnly: "32×32 预览",
  download: "下载图片",
  deleteImage: "删除图片",
  participants: "匿名成员",
  owner: "匿名 Owner",
  guest: "匿名 Guest",
  you: "你",
  online: "在线",
  offline: "离线",
  kickMember: "移出房间",
  latency: "延迟",
  activity: "传输消息",
  noActivity: "暂无传输消息",
  testMessage: "发送文本消息",
  textPlaceholder: "输入消息",
  sendMessage: "发送",
  quickReactions: "快捷表情",
  messageSending: "等待对方确认",
  messageSent: "对方已接收",
  messageReceived: "收到普通消息",
  waiting: "等待另一位成员",
  connecting: "正在建立实时连接",
  connected: "实时通道已连接",
  failed: "连接失败",
  sending: "正在发送",
  receiving: "正在接收",
  complete: "传输完成",
  awaitingReceipt: "已发送，等待对方确认",
  cacheFailed: "本地缓存失败",
  transferFailed: "图片传输失败",
  imageOnly: "只能传输图片文件",
  tooLarge: "图片超过房间大小限制",
  temporaryLeave: "临时离开",
  closeRoom: "退出并销毁房间",
  confirmClose: "退出后房间将立即销毁，所有成员都会被移出。确定继续吗？",
};

const en: typeof zh = {
  back: "Back to home",
  room: "Share room",
  copy: "Copy room link",
  copied: "Link copied",
  shareCreatedTitle: "Share room created",
  shareLink: "Share link",
  expires: "This room expires in 30 minutes",
  closeDialog: "Close",
  invalid: "Invalid share link",
  workspace: "Image workspace",
  upload: "Choose images",
  uploading: "Sending",
  drop: "Drop images to transfer",
  dropHint: "Common image formats; the room sets the size limit",
  guestEmpty: "Choose or drop images",
  cached: "Images are stored in this browser",
  sent: "Sent",
  received: "Received",
  send: "Send image",
  waitingToSend: "Waiting to send",
  waitingForSender: "Waiting for sender",
  preparingPreview: "Preparing placeholder",
  previewFailed: "Placeholder generation failed",
  previewOnly: "32×32 preview",
  download: "Download image",
  deleteImage: "Delete image",
  participants: "Anonymous members",
  owner: "Anonymous Owner",
  guest: "Anonymous Guest",
  you: "You",
  online: "Online",
  offline: "Offline",
  kickMember: "Remove from room",
  latency: "RTT",
  activity: "Transfer messages",
  noActivity: "No transfer messages yet",
  testMessage: "Send a text message",
  textPlaceholder: "Type a message",
  sendMessage: "Send",
  quickReactions: "Quick reactions",
  messageSending: "Waiting for peer confirmation",
  messageSent: "Received by peer",
  messageReceived: "Regular message received",
  waiting: "Waiting for another member",
  connecting: "Establishing realtime connection",
  connected: "Realtime channel connected",
  failed: "Connection failed",
  sending: "Sending",
  receiving: "Receiving",
  complete: "Transfer complete",
  awaitingReceipt: "Sent, waiting for receiver confirmation",
  cacheFailed: "Local cache failed",
  transferFailed: "Image transfer failed",
  imageOnly: "Only image files can be transferred",
  tooLarge: "Image exceeds the room size limit",
  temporaryLeave: "Leave temporarily",
  closeRoom: "Exit and close room",
  confirmClose: "Closing the room removes every member immediately. Continue?",
};

export type ShareRoomLabels = typeof zh;

export function getShareRoomLabels(
  lang: Lang,
  maxImageTransferSize: number | null = null,
): ShareRoomLabels {
  const labels = lang === "zh" ? zh : en;
  if (!maxImageTransferSize) return labels;
  const sizeMb = maxImageTransferSize / 1024 / 1024;
  const sizeText = `${Number(sizeMb.toFixed(2))} MB`;
  return {
    ...labels,
    dropHint:
      lang === "zh"
        ? `支持常见图片格式，单张最大 ${sizeText}`
        : `Common image formats, up to ${sizeText} each`,
    tooLarge:
      lang === "zh"
        ? `图片超过 ${sizeText}`
        : `Image exceeds ${sizeText}`,
  };
}
