import React from "react";
import { FiCheck, FiClock, FiMessageCircle, FiUsers, FiX } from "react-icons/fi";
import type { Collaborator, WorkspaceActivity, WorkspaceCommit, WorkspaceIdentity, WorkspaceImage, WorkspaceProposal, WorkspaceRuntimeState } from "../types";
import { getLang, getWorkspaceLabels } from "../../locales";
import { WorkspaceActivityList } from "./workspace-activity-list";

const text = (key: string) => getWorkspaceLabels(getLang())[key] || key;

export function WorkspaceCollaborationPanel({ onlineCollaborators, proposals, role, runtime, onlinePeers, reactionCounts, messages, message, selectedCollaborationActivities, selectedOriginalCommit, selected, onClose, onRemoveCollaborator, onPreviewProposal, onDecideProposal, onRejectProposal, onRetryProposal, onReact, onPreviewActivity, onOpenOriginal, onMessageChange, onSendMessage }: {
  onlineCollaborators: Collaborator[]; proposals: WorkspaceProposal[]; role: WorkspaceIdentity["role"]; runtime: WorkspaceRuntimeState; onlinePeers: number; reactionCounts: Record<string, number>; messages: Array<{ id: string; actor: string; text: string }>; message: string; selectedCollaborationActivities: WorkspaceActivity[]; selectedOriginalCommit?: WorkspaceCommit; selected?: WorkspaceImage | null; onClose(): void; onRemoveCollaborator(person: Collaborator): void; onPreviewProposal(proposal: WorkspaceProposal): void; onDecideProposal(proposal: WorkspaceProposal, state: "approved" | "later"): void; onRejectProposal(proposal: WorkspaceProposal): void; onRetryProposal(proposal: WorkspaceProposal): void; onReact(emoji: string): void; onPreviewActivity(activity: WorkspaceActivity): void; onOpenOriginal(): void; onMessageChange(value: string): void; onSendMessage(): void;
}) {
  return <>
    <section className="border-b border-[#e4e7eb] p-4"><div className="flex items-center gap-2 text-sm font-semibold text-[#26344c]"><FiUsers /><span>{text("collaboration")}</span><button type="button" onClick={onClose} className="flex h-8 w-8 items-center justify-center rounded-md text-slate-500 hover:bg-slate-100"><FiX /></button></div></section>
    <section className="border-b border-[#e4e7eb] p-4"><div className="mb-3 text-[11px] font-bold uppercase text-[#778294]">{text("collaborators")}</div>{onlineCollaborators.length ? onlineCollaborators.map((person) => <div key={person.clientId} className="flex items-center gap-2 py-1.5 text-sm"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-slate-100 text-[10px] font-bold text-slate-600">{person.displayName.slice(0, 2).toUpperCase()}</span><span className="min-w-0 flex-1"><strong className="block truncate text-xs text-slate-800">{person.displayName}</strong><span className="block truncate text-[10px] text-slate-400">{person.currentAction || text("viewingWorkspace")}</span></span><i className="h-2 w-2 rounded-full bg-emerald-500" />{role === "owner" && person.role === "collaborator" ? <button type="button" onClick={() => onRemoveCollaborator(person)} className="flex h-7 w-7 items-center justify-center rounded-md text-slate-400 hover:bg-red-50 hover:text-red-600" title={text("removeCollaborator")} aria-label={`Remove ${person.displayName}`}><FiX /></button> : null}</div>) : <p className="text-xs text-slate-500">{text("noCollaborators")}</p>}</section>
    {proposals.length ? <section className="border-b border-[#e4e7eb] p-4"><div className="flex items-center gap-2 text-[11px] font-bold uppercase text-[#778294]"><FiClock />{text("pendingProposals")}</div><div className="mt-2 grid gap-1.5">{proposals.slice().reverse().map((proposal) => <div key={proposal.proposalId} className="rounded-md border border-slate-200 bg-slate-50 p-2 text-xs"><div className="flex items-center justify-between gap-2"><strong className="truncate">{proposal.operations.map((op) => op.type).join(", ")}</strong><span className="text-[10px] text-slate-500">{proposal.state}</span></div>{role === "owner" && ["submitted", "pending", "later", "conflict"].includes(proposal.state) ? <div className="mt-2 flex flex-wrap gap-1"><button type="button" onClick={() => onPreviewProposal(proposal)} className="rounded border bg-white px-2 py-1">{text("preview")}</button><button type="button" onClick={() => onDecideProposal(proposal, "approved")} className="rounded bg-emerald-50 px-2 py-1 text-emerald-700">{text("approve")}</button><button type="button" onClick={() => onRejectProposal(proposal)} className="rounded bg-red-50 px-2 py-1 text-red-700">{text("reject")}</button><button type="button" onClick={() => onDecideProposal(proposal, "later")} className="rounded bg-slate-200 px-2 py-1">{text("later")}</button></div> : role === "collaborator" && proposal.state === "failed" ? <button type="button" onClick={() => onRetryProposal(proposal)} disabled={runtime !== "available"} className="mt-2 rounded border bg-white px-2 py-1 disabled:opacity-40">{text("retry")}</button> : null}</div>)}</div></section> : null}
    <section className="border-b border-[#e4e7eb] p-3"><div className="flex gap-2">{["👍", "❤️", "👀", "✅", "❗"].map((emoji) => { const count = reactionCounts[emoji] || 0; return <button type="button" key={emoji} disabled={!onlinePeers} onClick={() => onReact(emoji)} className="flex h-10 min-w-0 flex-1 items-center justify-center gap-1 rounded-md bg-slate-100 px-1 transition hover:bg-blue-50 disabled:opacity-30"><span>{emoji}</span>{count ? <span className="text-[10px] font-bold tabular-nums text-slate-500">+{count}</span> : null}</button>; })}</div></section>
    <section className="flex min-h-[260px] flex-col"><div className="min-h-0 flex-1 overflow-y-auto p-4"><div className="mb-2 text-[11px] font-bold uppercase text-[#778294]">{text("activity")}</div><WorkspaceActivityList activities={selectedCollaborationActivities} proposals={proposals} role={role} originalCommit={selectedOriginalCommit} currentCommitId={selected?.currentCommitId} canRollback={role === "owner" && selectedOriginalCommit?.commitId !== selected?.currentCommitId} onActivity={onPreviewActivity} onOriginal={onOpenOriginal} /><div className="mb-2 mt-5 text-[11px] font-bold uppercase text-[#778294]">{text("messages")}</div>{messages.length ? messages.map((item) => <div key={item.id} className="mb-3 text-xs"><strong>{item.actor}</strong><p className="mt-0.5 text-slate-600">{item.text}</p></div>) : <p className="text-xs text-slate-400">{text("noMessages")}</p>}</div><div className="flex gap-2 border-t p-3"><input value={message} onChange={(event) => onMessageChange(event.target.value)} onKeyDown={(event) => event.key === "Enter" && onSendMessage()} disabled={!onlinePeers} className="h-9 min-w-0 flex-1 rounded-md border px-3 text-xs" placeholder={text("typeMessage")} /><button type="button" onClick={onSendMessage} disabled={!onlinePeers || !message.trim()} className="flex h-9 w-9 items-center justify-center rounded-md bg-[#2f65cf] text-white disabled:opacity-30"><FiMessageCircle /></button></div></section>
  </>;
}
