import React from "react";
import { FiArrowRight, FiChevronLeft, FiChevronRight, FiImage, FiUploadCloud } from "react-icons/fi";
import type { WorkspaceIdentity, WorkspaceImage } from "../types";
import { getLang, getWorkspaceLabels } from "../../locales";
import { WorkspaceGalleryCard, type WorkspaceCardOperation } from "./workspace-gallery-card";
import { WorkspaceLibraryItem } from "./workspace-library";

const text = (key: string) => getWorkspaceLabels(getLang())[key] || key;

export function WorkspaceGallery({ libraryCollapsed, libraryImages, workingImages, workingImagesSorted, selectedId, role, dragging, onlinePeers, requestingSourceIds, collaborationPreviewFor, onToggleLibrary, onUpload, onDragEnter, onDragOver, onDragLeave, onDrop, onSelect, onAddToWorking, onDeleteLibrary, onPin, onMoveToLibrary, onRequestSource, onDownload, onMaximize, onOperation }: {
  libraryCollapsed: boolean; libraryImages: WorkspaceImage[]; workingImages: WorkspaceImage[]; workingImagesSorted: WorkspaceImage[]; selectedId?: string | null; role: WorkspaceIdentity["role"]; dragging: boolean; onlinePeers: number; requestingSourceIds: Set<string>; collaborationPreviewFor(image: WorkspaceImage): Blob | undefined; onToggleLibrary(): void; onUpload(): void; onDragEnter(event: React.DragEvent<HTMLDivElement>): void; onDragOver(event: React.DragEvent<HTMLDivElement>): void; onDragLeave(event: React.DragEvent<HTMLDivElement>): void; onDrop(event: React.DragEvent<HTMLDivElement>): void; onSelect(imageId: string): void; onAddToWorking(image: WorkspaceImage): void; onDeleteLibrary(image: WorkspaceImage): void; onPin(image: WorkspaceImage): void; onMoveToLibrary(image: WorkspaceImage): void; onRequestSource(image: WorkspaceImage): void; onDownload(image: WorkspaceImage): void; onMaximize(image: WorkspaceImage): void; onOperation(image: WorkspaceImage, operation: WorkspaceCardOperation): void;
}) {
  return <div className={`grid min-h-[360px] flex-1 overflow-hidden rounded-lg border-2 border-dashed bg-white/80 transition ${dragging ? "border-[#2f65cf] bg-blue-50" : "border-[#c9d0da]"} ${libraryCollapsed ? "sm:grid-cols-[44px_minmax(0,1fr)]" : "sm:grid-cols-[240px_minmax(0,1fr)]"}`} onDragEnter={onDragEnter} onDragOver={onDragOver} onDragLeave={onDragLeave} onDrop={onDrop}>
    {libraryCollapsed ? <aside className="hidden min-h-0 flex-col items-center border-r border-slate-200 bg-slate-50/80 pt-2 sm:flex"><button type="button" onClick={onToggleLibrary} className="flex h-7 w-7 items-center justify-center rounded-md text-slate-400 hover:bg-white hover:text-[#2f65cf]" title={text("originLibrary")}><FiChevronRight /></button><button type="button" onClick={role === "owner" ? onUpload : undefined} className="relative mt-2 flex h-8 w-8 items-center justify-center rounded-md text-slate-400 hover:bg-white hover:text-[#2f65cf]" title={text("originLibrary")}><FiImage />{libraryImages.length ? <span className="absolute -right-1 -top-1 min-w-4 rounded-full bg-[#2f65cf] px-1 text-center text-[8px] text-white">{Math.min(libraryImages.length, 99)}</span> : null}</button></aside> : <aside className="hidden min-h-0 min-w-0 flex-col border-r border-slate-200 bg-slate-50/80 sm:flex"><div className="flex items-start justify-between border-b border-slate-200 p-3"><div className="min-w-0"><h2 className="text-xs font-semibold text-slate-800">{text("originLibrary")}</h2><p className="mt-0.5 text-[10px] leading-4 text-slate-500">{text("chooseOriginal")}</p></div><button type="button" onClick={onToggleLibrary} className="flex h-7 w-7 shrink-0 items-center justify-center rounded-md text-slate-400 hover:bg-white hover:text-[#2f65cf]" title={text("originLibrary")}><FiChevronLeft /></button></div><div className="min-h-0 flex-1 overflow-y-auto p-2">{libraryImages.length ? libraryImages.map((image) => <WorkspaceLibraryItem key={image.imageId} image={image} role={role} selected={selectedId === image.imageId} onSelect={() => onSelect(image.imageId)} onAdd={() => onAddToWorking(image)} onDelete={() => onDeleteLibrary(image)} />) : role === "owner" ? <button type="button" onClick={onUpload} className="flex h-full min-h-40 w-full flex-col items-center justify-center gap-2 p-4 text-center text-slate-400 hover:bg-white/70 hover:text-[#2f65cf]"><span className="flex h-10 w-10 items-center justify-center rounded-md bg-blue-50"><FiImage /></span><strong className="text-xs text-slate-700">{text("chooseOrDropOriginals")}</strong><span className="text-[10px]">{text("pngFormats")}</span></button> : <div className="flex h-full min-h-40 items-center justify-center p-4 text-center text-xs text-slate-400">{text("originImagesOwner")}</div>}</div></aside>}
    <section className="flex min-h-0 min-w-0 flex-col" aria-label={text("workingProcessing")}><div className="flex h-[58px] shrink-0 items-center justify-between border-b border-slate-200 px-4"><div><h2 className="text-xs font-semibold text-slate-800">{text("workingProcessing")}</h2><p className="mt-0.5 text-[10px] text-slate-500">{text("processCollaborate")}</p></div><span className="rounded bg-slate-100 px-2 py-1 text-[10px] font-semibold text-slate-500">{workingImages.length}</span></div><div className="min-h-0 min-w-0 flex-1 overflow-y-auto">{workingImages.length ? <div className="grid grid-cols-[repeat(auto-fill,minmax(min(100%,240px),1fr))] gap-x-8 gap-y-4 p-4 sm:pr-8">{workingImagesSorted.map((image) => <WorkspaceGalleryCard key={image.imageId} image={image} role={role} selected={selectedId === image.imageId} onlinePeers={onlinePeers} requestingSource={requestingSourceIds.has(image.imageId)} renderedBlob={collaborationPreviewFor(image)} onSelect={() => onSelect(image.imageId)} onPin={() => onPin(image)} onMoveToLibrary={() => onMoveToLibrary(image)} onRequestSource={() => onRequestSource(image)} onDownload={() => onDownload(image)} onMaximize={() => onMaximize(image)} onOperation={(operation) => onOperation(image, operation)} />)}</div> : <div className="flex min-h-[300px] h-full w-full flex-col items-center justify-center px-6 text-center text-slate-400"><FiArrowRight className="mb-3 h-7 w-7" /><strong className="text-sm text-slate-600">{text("workingEmpty")}</strong><span className="mt-1 text-xs">{text("addFromOrigin")}</span></div>}</div></section>
  </div>;
}
