packages:
  - "."
  - "../sdk/room"
  - "../sdk/wasm/image-codecs"
  - "../sdk/wasm/image-wasm"
  - "../sdk/wasm/perceptual-wasm"
enableGlobalVirtualStore: false
allowBuilds:
  "@parcel/watcher": true
  "esbuild": true
  "sharp": true
  "unrs-resolver": true
